### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [shrutipanchal7699/CMPE131#1]

**Comment by shrutipanchal7699** [comment]
group number 5 and class section is 05

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by Renncia** [comment]
Hello. -Christian

**Comment by gggonzalez03** [comment]
Hello - Ging

**Comment by qnguyen3411** [comment]
Hello - Quang

**Comment by ProfRojas** [comment]
Thanks!
